"""Optimize complete existing outfit photos for mapping. No generation or warp."""
from pathlib import Path
import hashlib, json
from PIL import Image, ImageDraw, ImageFont
ROOT=Path(__file__).resolve().parents[1]
LOOKS=[
 ('ao-dai','female','aodai1.png','Áo dài',[]),
 ('ao-dai','female','aodai2.png','Áo dài + nón lá',['non-la']),
 ('ao-ba-ba','female','aobaba.png','Áo bà ba',[]),
 ('ao-ngu-than','female','aonguthan_female.png','Áo ngũ thân nữ',[]),
 ('ao-ngu-than','male','aonguthan_male.png','Áo ngũ thân nam',[]),
 ('ao-giao-linh','female','aogiaolinh_female.png','Áo giao lĩnh nữ',[]),
 ('ao-giao-linh','male','aogiaolinh_male.png','Áo giao lĩnh nam',[]),
 ('ao-nhat-binh','female','aonhatbinh.png','Áo Nhật Bình',[]),
 ('ao-tu-than','female','aotuthan.png','Áo tứ thân',[]),
 ('ao-yem','female','vaydup_aoyiem.png','Áo yếm + váy',[]),
]
def build():
 target=ROOT/'assets/web';target.mkdir(exist_ok=True)
 records=[];sheet=Image.new('RGB',(1250,1400),'white');draw=ImageDraw.Draw(sheet)
 try:font=ImageFont.truetype('C:/Windows/Fonts/arial.ttf',18)
 except OSError:font=ImageFont.load_default()
 for i,(id,gender,filename,name,accessories) in enumerate(LOOKS):
  path=ROOT/'assets'/filename;photo=Image.open(path).convert('RGB')
  photo.thumbnail((720,1200),Image.Resampling.LANCZOS)
  key=gender+'-'+id+('-non-la' if accessories else '')
  photo.save(target/(key+'.webp'),'WEBP',quality=87,method=6)
  records.append({'key':key,'costumeId':id,'gender':gender,'name':name,'accessories':accessories,
   'sourceFile':'assets/'+filename,'sourceSha256':hashlib.sha256(path.read_bytes()).hexdigest(),
   'file':'assets/web/'+key+'.webp','width':photo.width,'height':photo.height,
   'mode':'complete-photo-mapping','hasExistingBackground':True,'sources':[],'needsVerification':True,
   'verificationTodo':'TODO: bổ sung nguồn văn hóa cho mẫu người dùng cung cấp.',
   'preparation':{'uniformResize':True,'crop':False,'warp':False,'generated':False}})
  thumb=photo.copy();thumb.thumbnail((230,630),Image.Resampling.LANCZOS)
  sheet.paste(thumb,(i%5*250+(250-thumb.width)//2,i//5*700+45))
  draw.text((i%5*250+10,i//5*700+10),name,fill='#302826',font=font)
 manifest={'schemaVersion':1,'sources':[],'needsVerification':True,'items':records,
  'notice':'Mapping ảnh hoàn chỉnh. Tổ hợp chưa có ảnh tương ứng dùng mẫu mặc định, không sinh ảnh.'}
 (target/'photo-catalog.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
 (ROOT/'viet-phuc-remix/js/photoMappingData.js').write_text('// Generated by tools/build_photo_catalog.py. No image generation.\nwindow.VietPhucPhotoMappingData='+json.dumps(records,ensure_ascii=False,indent=2)+';\n',encoding='utf-8')
 sheet.save(ROOT/'assets/review/current-web-looks.jpg',quality=91)
 inventory=[]
 for path in sorted((ROOT/'assets').iterdir()):
  if path.suffix.lower() not in ('.png','.jpg') or path.name in ('inventory-contact.png','review-natural-fit.png'):continue
  with Image.open(path) as im:
   inventory.append({'file':'assets/'+path.name,'width':im.width,'height':im.height,'mode':im.mode,
    'bytes':path.stat().st_size,'sha256':hashlib.sha256(path.read_bytes()).hexdigest(),
    'sources':[],'needsVerification':True,'status':'mapped-photo' if any(r['sourceFile']=='assets/'+path.name for r in records) else 'available-for-later-upgrade'})
 (target/'source-inventory.json').write_text(json.dumps({'items':inventory},ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
 print(f'{len(inventory)} sources; {len(records)} mapped photos; {sum((ROOT/r["file"]).stat().st_size for r in records)} optimized bytes')
if __name__=='__main__':build()
